#development:
#  access_key_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#  secret_access_key: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

#test:
#  access_key_id: abc
#  secret_access_key: abc/efg

production:
  access_key_id: WWWWWWWWWW
  secret_access_key: RRRRRRRRRRRRRR
